### ISSUE TITLE
Can we use this package in backend api project ?

### ISSUE THREAD

**Issue by siva-sankaran** [AdrianDucao/sessionStorage-for-node#1]
I am developing a backend REST API project.  I want to store some information related to currently logged in User.  I tried this package but not accessing in subsequent api  requests.

**Comment by AdrianDucao** [comment]
what do you mean not accessing in subsequent api request? because sessionStorage is only stored in the browser and typically cleared when the page session ends

**Comment by AdrianDucao** [comment]
> I am developing a backend REST API project. I want to store some information related to currently logged in User. I tried this package but not accessing in subsequent api requests.

if i understand you correctly you want to use sessionStorage to store some user information who's currently logged in and should persist on subsequest api request with the same logged in user? or would that be a new user who's logged in?

**Comment by siva-sankaran** [comment]
> if i understand you correctly you want to use sessionStorage to store some user information who's currently logged in and should persist on subsequest api request with the same logged in user?

Yes

Is this package meant to be used for client apps i.e. front end app ?  I want to use in server side( backend)

**Comment by AdrianDucao** [comment]
> > if i understand you correctly you want to use sessionStorage to store some user information who's currently logged in and should persist on subsequest api request with the same logged in user?
> 
> Yes
> 
> Is this package meant to be used for client apps i.e. front end app ? I want to use in server side( backend)

yeah i'm afraid this is only intended for client side use, you could just use databases like mongodb or mysql
